### ISSUE TITLE
desugarSwitch produces invalid JavaScript or wrong output

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/Stopify#29]
It may be the case that a subsequent transformation deals with the output of desugarSwitch. However, when applied in isolation, desugarSwitch produces invalid JavaScript. This will be an issue if we want to use it to do the Pyret-style transformation.

The high-level issue is that desugarSwitch eliminates the `switch` statement but leaves enclosing `break;` statements intact. A `break;` statement jumps out of the innermost enclosing loop or `switch` statement. So, with the switch eliminated, we either get (1) a syntax error if there is no enclosing loop or (2) wrong result, if we jump out of an enclosing loop.

The solution would be to enclose the output from desugarSwitch in a labelled block and turn the `break;`s into labelled breaks.

Here is the smallest example. This program, which does not raise an error:
```
function f() {
  switch(0) {
  case 0:
    break;
  }
}

f();
```

Is transformed to this program, which raises a SyntaxError:
```
function f() {
  {
    let _test = 0;
    let _fallthrough = false;

    if (_test === 0 || _fallthrough) {
      _fallthrough = true;

      break;
    }
  }
}

f();
```

**Comment by baxtersa** [comment]
> The solution would be to enclose the output from desugarSwitch in a labelled block and turn the break;s into labelled breaks.

This is handled in a prior transform, `desugarLabels`. We should at least figure out a better way of documenting dependencies among babel visitors, and probably look into consolidating this logic into a single pass so that it works in isolation. Haven't thought about or looked at how much they could be merged yet though.

**Comment by arjunguha** [comment]
This is all good. Thanks. No need to change anything.

**Comment by rachitnigam** [comment]
@sbaxter if there is a dependency between the two transforms, they should be merged. Two dependent transforms should not be separated unless absolutely necessary.

**Comment by rachitnigam** [comment]
Reopening because of my prior comment.

**Comment by baxtersa** [comment]
@rachitnigam , it's not that easy. There are a handful of desugars which involve two-stage plugins right now, it's not just this one. I'm closing this and opening a specific issue to look into consolidating desugars to map one-to-one to visitors.
