### ISSUE TITLE
Remaining compilers for the third-party-compiler-container

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/Stopify#296]
- [ ] scheme2js
- [ ] JSweet

**Comment by arjunguha** [comment]
In case it isn't obvious, I hope that we can use this compiler-container for the demo, evaluation, and regular development. To really support these use-cases, the compiler-container probably needs to cache programs, which we can do next.

**Comment by baxtersa** [comment]
Migrated to `stopify.org` repo
