### ISSUE TITLE
HandleNew implementation should be abstracted from Runtimes.

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Stopify#306]
The new runtime interface has this really nice property that allows it to separate the technique for unwinding the stack and how values in `capture`, `restore`, and `normal` mode are collected.

This become really handy when implementing the DeepRuntimes. In fact, with the new implementation, the files for lazyDeepRuntime and lazyRuntime are *almost* the same save for the definition of handleNew.

This suggests that by abstracting away the implementation into something else, we could get Shallow and Deep runtimes for free.

**Comment by arjunguha** [comment]
This is done, right?
