### ISSUE TITLE
Change $gs.get_prop to take a thunk.

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Stopify#330]
Instead of the current implementation of getters and setters where: `a.b => $gs.get_prop(a, "b")`, do the following: `$gs.get_prop(() => a.b)`. 

Doing this side steps the `prototype` binding issues with the current implementation.

**Comment by baxtersa** [comment]
This isn't going to fix anything. You're still aliasing the property access and calling the function on the alias, which loses the binding. The application needs to be made with `.call` to restore the binding. Closing this and leaving the other issue.
