### ISSUE TITLE
Documentation: Which OCaml compiler?

### ISSUE THREAD

**Issue by ShalokShalom** [plasma-umass/Stopify#347]
In our [FAQ](http://www.stopify.org/faq.html) you mention the OCaml compiler and that it aims a very simple subset of Javascript. Do you mean Bucklescript or Js_of_OCaml?

**Comment by arjunguha** [comment]
@ShalokShalom the demo website uses BuckleScript.

**Comment by ShalokShalom** [comment]
Its about your documentation.

**Comment by rachitnigam** [comment]
@ShalokShalom The FAQ is talking about the simple subset of JS targeted by BuckleScript.

**Comment by arjunguha** [comment]
@ShalokShalom you're right. We'll add acks for BuckleScript and the other compilers soon.

**Comment by arjunguha** [comment]
fixed at last!
