### ISSUE TITLE
Preserve stack traces

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/Stopify#355]
Right now, Stopify can destroy JavaScript stack traces in several situations:

1. When deep stacks are enabled: if the program yields control, resumes execution, and then throws an exception, stack trace will not include the stack frames that are on reified to the heap.
2. Stopify's internal functions appear on stack traces.
3. Stopify does not preserve original line numbers.

I think we can address the first two entirely at runtime. There is likely to be some cost, so we may want it to be an optional feature.

The third feature probably requires compiler support. I think we need to serialize the source map and use it to patch stack traces.

Anyway, this would be a good starter project. The CodeHS and Pyret folks would appreciate this.

**Comment by arjunguha** [comment]
I've attached a trivial program that throws an uncaught exception. We get this stack trace, which is totally unreadable:

```
Error: omg
    at Object.fun0 [as box] (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:1873)
    at G (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:2454)
    at $top (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:2726)
    at LazyRuntime.abstractRun (stopify-full.bundle.js:54952)
    at LazyRuntime.runtime (stopify-full.bundle.js:1722)
    at eval (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:2978)
    at Runner.run (stopify-full.bundle.js:27886)
    at error-lines.html:20
```

I don't think we need to turn it into the stack trace that the program would have produced without Stopify.  But, we do need to clean it up. Here is the original program:

```
function F() {
    throw new Error('omg');
}

function G() {
  F();
  }

  G();
```

And here are the lines of code in user code:

```
    at Object.fun0 [as box] (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:1873)
    at G (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:2454)
    at $top (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:2726)
    at eval (eval at run (stopify-full.bundle.js:27886), <anonymous>:1:2978)
```

i.e., the user code is eval'd and we currently do not pretty-print, thus everything is on one line. Note that the name `Object.fun0 [as box]` comes from `F` getting boxed.

[error-lines.html.txt](https://github.com/plasma-umass/Stopify/files/2012789/error-lines.html.txt)

**Comment by arjunguha** [comment]
Here is an idea for preserving stack traces:

1. Always parse the sourcemap (even `.debug == false`)
2. Add a field `stackTrace: string[]` to the runtime system
3. In jumper with exceptional continuations, when an ordinary exception (i.e., not `Capture`) is thrown, emit the statement `rts.stackTrace.push(name + " : " + line);` before the exception is currently rethrown. Here, `line` is  `s.opts.sourceMap.getLine(loc.start.line, loc.start.column)` and `name` is the name of the enclosing function (i.e., `path.getFunctionParent()`). 
4. In jumper with non-exceptional continuations, we will have to wrap all function calls with a try/catch block that does what is described above and rethrow.

Caveat: if the current function is boxed then `path.getFunctionParent()` will not produce the right function. We can hack around this by adding an "original-name" attribute to functions in the boxing phase.

Thoughts from @jpolitz @baxtersa @rachitnigam ?

**Comment by arjunguha** [comment]
I should add that we may not want to do things this way. In JavaScript, throwing an exception *does not* record the stack trace. Instead, all you need to do is create a `new Error()` object. We could do something of this kind. For example, we could simply record the stack trace in every captured continuation (i.e., alongside the locals, target, and restore function for each frame).

**Comment by arjunguha** [comment]
Ultimately, we want exceptions thrown from non-stopified code to play well with stopified code. It would be annoying if non-stopified code required a shim for stack traces to work well.  I imagine that the simplest approach would be as follows:

1. Non-stopified code throws an exception (may or may not be an error object)
2. Stopify catches the error and starts building a stack trace as described.
3. If the exception is unhandled, the `onDone` callback passed to `AsyncRun.run` received the exception value and the stack trace captured by Stopify.
4. If the exception is handled, Stopify's stack trace is discarded.

**Comment by rachitnigam** [comment]
There might issues with uninstrumented functions. For example, if an uninstrumented function throws an exception, how will Stopify add its information to the stack trace?

One solution may be to disable optimization completely, but that seems too costly.

**Comment by arjunguha** [comment]
Right, we would have to instrument *all* throws. Moreover, all function applications would need to be instrumented save the stack trace. We have the option of building the stack trace eagerly (i.e., without using exception handlers). That might be best.

**Comment by baxtersa** [comment]
This is done right?

**Comment by arjunguha** [comment]
Right. It is working just fine for us in Ocelot.
