### ISSUE TITLE
Split stopify/stopify-continuations into separate compiler/runtime packages

### ISSUE THREAD

**Issue by baxtersa** [plasma-umass/Stopify#394]
For browser-consumption, we webpack runtime/compiler package entrypoints to reduce the bloat of including stopify in a webpage. In the serverless context, people typically install npm dependencies and deploy a zip of all of `node_modules` and the function's source code.

Right now, installing `stopify` or `stopify-continuations` as a package dependency pulls in all of `babel` and it's many packages. Programs that consume just the runtime part of `stopify` and `stopify-continuations` therefore pull in over 10 MB of unnecessary dependencies (assuming the runtime doesn't need the compiler, which isn't the case if you want to support `eval`).

I propose we separate the compiler and runtime portions of `stopify` and `stopify-continuations` into distinct yarn workspaces, so we can deploy and install them as separate npm packages. This way consumers of just the runtime portion don't suffer large bloat in `node_modules`, causing slow deploy times/container init times in serverless contexts.

I'm happy to do this work. I already have some local work fixing dependencies in the various `package.json` files for each workspace.

Open to feedback. @arjunguha , is this going to conflict with any of the things you're doing?

**Comment by arjunguha** [comment]
Sounds reasonable. Are you trying to pull this off before you leave IBM?

**Comment by baxtersa** [comment]
likely not. Other things are priority before leaving, but it will be one of the first things I work on after picking it back up.

**Comment by arjunguha** [comment]
OK. After you return, I want to discuss merging this branch too:

https://github.com/plasma-umass/Stopify/commits/220

It involves changes to stopify-continuations that may make sense to merge
before your runtime surgery. I am definitely not going to merge anything
until classes start.

**Comment by baxtersa** [comment]
Done
