### ISSUE TITLE
yield pass: Top level function application for non-generator functions get turned into run calls

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Stopify#4]
This happens when the function being called is not declared in the file. Consider the program:
```[javascript]
let assert = require('assert');
assert(true)
```
which gets turned into:
```
let assert = require('assert');
let gen  = assert(true)
run(gen)
```
which is incorrect. 

Need to do something about it.

**Comment by baxtersa** [comment]
For this and other cases (thinking about adding continuation args to function calls), we may want to do a pass and tag applications of free identifiers in function position as `ignore` for future transformations. This would handle things like `console.log`, etc.

**Comment by rachitnigam** [comment]
As a first pass, yes. We do want to think about FFIs at some point (I.e. Code that hasn't been transformed).
