### ISSUE TITLE
"Step" in JavaScript demo not working

### ISSUE THREAD

**Issue by joshlory** [plasma-umass/Stopify#406]
On http://www.stopify.org/ I'm not able to get the "Step" button to work, even after clicking "Run" and "Stop".

In the console I get http://www.stopify.org/mode-js.js is 404 not found.

**Comment by baxtersa** [comment]
Hi Josh, thanks for the report! I did a quick check and this works for me in Firefox, in Safari I get the same errors as you. Can you report if you were also trying in Safari?

I can try to fix this issue this week.

**Comment by joshlory** [comment]
Thank you for the quick response!  I originally hit the issue in Chrome 68.  I'm getting the same issue in Firefox 61.

In Firefox, trying to "Step" from a breakpoint:

![image](https://user-images.githubusercontent.com/413693/45331005-1cffb800-b51d-11e8-9ebd-aa97995bd45a.png)

Could very well be user-error on my part 😄.

**Comment by joshlory** [comment]
@baxtersa following up — thank you!

**Comment by baxtersa** [comment]
Hi Josh, sorry for the long delay here! PR #415 is preparing to release a new version of stopify that fixes this issue. Once that PR lands, I'll have to deploy new packages to npm and update the website to use the latest version. I'll keep you posted once that is taken care of.

Thanks for reporting the issue!

**Comment by arjunguha** [comment]
I believe this is now fixed.
