### ISSUE TITLE
[Feature Request] Running Stopify in a worker

### ISSUE THREAD

**Issue by jpolitz** [plasma-umass/Stopify#434]
I'm sketching out a use of Pyret's compiler inside a web worker, and would like to use Stopify in a worker as well. Doing `var stopify = require('stopify');`, packing things up with `browserify`, and then loading in a worker leads to 

```
Uncaught ReferenceError: window is not defined
    at makeSetImmediatePM
    at makeSetImmediate
...
```

I think a fix is to do some check for being in a worker, and just default to makeSetImmediateT0. If I force `window` to have a `setImmediate` property way by declaring `window` as a variable, then stopify seems to load correctly (which is terrific). I'm not sure what the best check for being in a worker is (e.g. https://stackoverflow.com/questions/7931182/reliably-detect-if-the-script-is-executing-in-a-web-worker), but I think some simple check could suffice to make this work well.

**Comment by arjunguha** [comment]
Should be easy enough to do, and I can take care of this this week. I am interested in using this as well.

**Comment by jpolitz** [comment]
This works for me now, sorry for the delay.

**Comment by arjunguha** [comment]
Merged in the commit. I'll do a bit more work then re-release.
