### ISSUE TITLE
Quick Start example broken

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Stopify#447]
The Quick start example needs the following the HTML code:

```html
<html>
  <body>
    <script src="stopify.bundle.js"></script>
    <script>
    var runner = stopify.stopify("output.js");
    runner.g = { console, document, Date }; 
    runner.run(() => console.log("done"));
    </script>
  </body>
</html>
```

Without this, the page doesn't display anything.

**Comment by arjunguha** [comment]
Did you fix it already?

![image](https://user-images.githubusercontent.com/20065/65790579-ed265100-e12d-11e9-9c86-163baae5ade7.png)

**Comment by rachitnigam** [comment]
No, I haven't had the chance to do. If you point me to the file, I'll can open a PR.

**Comment by arjunguha** [comment]
No, I mean the example seems to be in readthedocs. Can you link to the broken example?

**Comment by rachitnigam** [comment]
Here: https://stopify.readthedocs.io/en/latest/quickstart.html

**Comment by arjunguha** [comment]
Ah, I see. You need to set the globals array. Thanks for spotting that. Would you submit a PR? It's in the /docs directory. Should be easy.
