### ISSUE TITLE
Uncaught capture

### ISSUE THREAD

**Issue by oflatt** [plasma-umass/Stopify#464]
This is either a bug or a misuse of the library:

I'm trying to run the sleep example, but completely stop execution after 3 seconds.
```function sleep(duration) {
      asyncRun.pauseImmediate(() => {
        window.setTimeout(() => asyncRun.continueImmediate({ type: 'normal', value: undefined }), duration);
      });
    }

    const program = `
      while(true) {
        sleep(1000);
        document.body.appendChild(document.createTextNode("."));
      }
    `;

    const asyncRun = stopify.stopifyLocally(program);
    asyncRun.g = { sleep, document, window, asyncRun };

      asyncRun.run(() => { });

      setTimeout(() => {asyncRun.pauseImmediate();}, 3000);
```

When I run this, I get a console error after 3 seconds and execution continues
![image](https://user-images.githubusercontent.com/8523445/85620285-cc3d4e80-b620-11ea-9ec8-8c84ccdc7cc8.png)

Is this a misuse of the `runner`? If so, how do you stop a runner completely? I'd like it to get garbage collected.

**Comment by arjunguha** [comment]
Hi! What follows is a working example. This is both a bug and a misuse of the library. :)

1. Misuse: Note that I'm using `.pause` and not `.pauseImmediate`. pauseImmediate only works within stopified code. Use pause to pause/stop the program "from the outside", which is what your program is doing.

2. Bug: I've passed some additional configuration options to stopifyLocally. They shouldn't be needed -- so that's a bug in the Stopify runtime system.

```
<html>
  <body>
    <script src="../../stopify/dist/stopify-full.bundle.js"></script>
    <script>
    function sleep(duration) {
      asyncRun.pauseImmediate(() => {
        window.setTimeout(
          () =>  asyncRun.continueImmediate({ type: 'normal', value: undefined }), 
	        duration);
      });
    }

    const program = `
      while(true) {
        sleep(1000);
        document.body.appendChild(document.createTextNode("."));
      }
    `;

   
    const asyncRun = stopify.stopifyLocally(program, {}, {
      estimator: "exact",
      yieldInterval: 200
    });
    asyncRun.g = { sleep, document, window, asyncRun };

    asyncRun.run(() => { });

    window.setTimeout(() => {
      asyncRun.pause(() => {
        document.body.appendChild(document.createTextNode("paused"));
      });
    }, 3000);
    </script>
  </body>
</html>
```

**Comment by oflatt** [comment]
Thanks! 
Also, how do I ensure that the thread gets cleaned up after I pause it? I'd like to throw it away, as the user is going to run a fresh instance. So far I've been storing the `asyncRun` variable on the `window`, then pausing it when I want to start a new run.

**Comment by arjunguha** [comment]
For what you have in this example, it should be adequate to write `asyncRun = undefined`, and let the JavaScript GC clean up.

It gets more complicated if the stopified code has setup repeatable event handlers (e.g., move move, or mouse click). In that case, you would need to unregister those event handlers as well.

**Comment by oflatt** [comment]
Thanks!
