### ISSUE TITLE
Only example from stopify manual fails when using webpack

### ISSUE THREAD

**Issue by LeifAndersen** [plasma-umass/Stopify#475]
So it looks like Stopify example from the manual doesn't work with webpack. Namely, I get a `Uncaught ReferenceError: stopify is not defined` error when running `stopify.run()`.

This is the script I'm running it in.

```
import * as stopify from '@stopify/stopify';

const runner = stopify.stopifyLocally("1+2");
runner.g = {};
console.log("Here");
runner.run(() => { console.log("ran") });
console.log("There");
```

The html for is just:

```
<!doctype html>

<script src="bundle.js"></script>
```

For reference, here is the whole codebase:

https://github.com/LeifAndersen/hello-stopify

You can run:

```
npm install
npx webpack -d
open dist/index.html
```

to see the error yourself.

Am I missing something or is this a bug?

Thanks.

**Comment by arjunguha** [comment]
I've seen this before.

Add a `window.stopify = stopify;` before the `const runner = ...;` line.

We do something similar in ElementaryJS:

https://github.com/umass-compsci220/ElementaryJS/blob/master/src/index.ts#L22

**Comment by LeifAndersen** [comment]
That worked perfectly, thank you.

It might be worth looking into why stopify assumes `stopify` is in the global namespace? Either that, or it might be worth mentioning that you need to add that somewhere in the manual.

Either way though, thanks for the help.
