### ISSUE TITLE
Memory Leak During Stopified Program Execution

### ISSUE THREAD

**Issue by InnPatron** [plasma-umass/Stopify#476]
Google Chrome  76.0.3809.87 (64-bit)
Ubuntu 18.04.02 LTS (64-bit)
Stopify version: @stopify/stopify 0.7.2 (npm)
Pyret version: [anchor commit 625ebc62363831dff99faa75d3401375e3632d2d](https://github.com/brownplt/pyret-lang/commit/625ebc62363831dff99faa75d3401375e3632d2d)

There appears to be a leak in Stopify's runtime causing performance degradation when trying to run Stopified Pyret programs: an increase of 50+ MB (and can be as severe as 150 MB) per run of the same program. Refreshing the page (creating a new JS instance) returns performance back to normal. (BTW, "fresh" performance is ~25% faster than the current public Pyret implementation at [CPO](https://code.pyret.org/).)

This is in comparison to a straightforward compilation to JavaScript which leaks in the KB range. 

The program I used for testing will be given upon request. Technically, it's a partial solution to a CS class homework, so I'd like to not expose it. It is basically a seam carving algorithm implementation.

Due to the sheer size of the data, here is a [link to a Google Drive folder](https://drive.google.com/drive/folders/1izWRZdM_4HW-ZJiuskz32UY7Pe256UHR?usp=sharing) containing:
1. A "before" heap snapshot
2. An "after" heap snapshot after the Stopified Pyret program has been executed
3. A performance timeline showing the memory climb

Some notes about the logs:
- The performance timeline was NOT captured from the same execution as the heap snapshots (this is due to machine limitations causing Chrome to crash)
- I don't have exact numbers but I don't think memory increase delta does has a pattern. Besides the number of times a program was run, nothing else changed.
- There is a visible pattern to the memory increase during execution: a gentle increase followed by a few giant leaps. If I'm reading the timeline correctly, these giant leaps appear to be occurring during frame restoration.
- The "after" heap snapshot is filled with Stopify stack frame objects about 10-16MB large.

Programs are run in the experimental IDE. To run:

1. Install the compiler dependencies (`npm install`)
2. Build the compiler (`npm run web`)
3. Install the IDE dependencies (`cd ide; npm install`)
4. Run the IDE (`cd ide; npm start`). Requires `chrome`'s path set via `$BROWSER`
5. Insert a program in the text box
6. Wait for auto-run or click the `Run` button

**Comment by arjunguha** [comment]
Sorry for the late response., I just noticed this. I assume you're working with @jpolitz and others. Since this involves a student submission, let's move this discussion to email. Send me an email at a.guha@northeastern.edu and CC anyone else who is involved.

**Comment by InnPatron** [comment]
No worries! 

Yes, I work for Joe. This is actually not a student submission, but a solution I came up with for an assignment. I'll email you and CC @jpolitz.

**Comment by jpolitz** [comment]
We are pretty sure we tracked this down, and both observed that this was a combo of React/Webpack hotloading and console.log causing the apparent leak.
